# Generated by Django 4.0 on 2023-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], default=1, verbose_name='Степень алкогольности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default_user.jpg', upload_to='users_photos', verbose_name='Аватар'),
        ),
    ]
