# Generated by Django 4.0 on 2023-02-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_character_alter_user_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_avatar/default_user.jpg', upload_to='users_photos', verbose_name='аватар'),
        ),
    ]
