# Generated by Django 4.0 on 2023-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='character',
            field=models.SmallIntegerField(choices=[(-1, 'Слушать'), (1, 'Говорить')], verbose_name='слушатель/говорун'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.SmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности'),
        ),
    ]
