# Generated by Django 4.0 on 2023-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_character_alter_user_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности'),
        ),
    ]
