# Generated by Django 4.0 on 2023-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], default=0, verbose_name='степень алкогольности'),
        ),
    ]
