# Generated by Django 4.0 on 2023-04-07 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название стойки')),
                ('degree', models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности')),
                ('about', models.CharField(blank=True, max_length=254, verbose_name='повестка')),
                ('quantity', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='количество участников за столом')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('picture', models.ImageField(default='bars_pictures/default_picture.jpg', upload_to='bars_pictures', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'барная стойка',
                'verbose_name_plural': 'барные стойки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='название')),
                ('degree', models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности')),
            ],
            options={
                'verbose_name': 'напиток',
                'verbose_name_plural': 'напитки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название темы')),
                ('tag', models.SlugField(verbose_name='сокращение (тег) для темы')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BarTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bar', verbose_name='бар')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theme', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'бар + тема',
                'verbose_name_plural': 'бары + темы',
            },
        ),
        migrations.CreateModel(
            name='BarParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='дата присоединения')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bar', verbose_name='бар')),
            ],
            options={
                'verbose_name': 'бар + участник',
                'verbose_name_plural': 'бары + участники',
            },
        ),
    ]
