# Generated by Django 4.0 on 2023-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='abbreviation',
            field=models.SlugField(max_length=7, verbose_name='Аббревиатура'),
        ),
        migrations.AddConstraint(
            model_name='userdrink',
            constraint=models.UniqueConstraint(fields=('user', 'drink'), name='unique_user_drink'),
        ),
        migrations.AddConstraint(
            model_name='userlanguage',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language'),
        ),
    ]
