# Generated by Django 4.0 on 2023-04-07 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barparticipant',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='участник'),
        ),
        migrations.AddField(
            model_name='bar',
            name='initiator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='own_bar', to='users.user', verbose_name='инициатор'),
        ),
        migrations.AddField(
            model_name='bar',
            name='participants',
            field=models.ManyToManyField(through='core.BarParticipant', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.AddField(
            model_name='bar',
            name='theme',
            field=models.ManyToManyField(through='core.BarTheme', to='core.Theme', verbose_name='темы разговора'),
        ),
        migrations.AddConstraint(
            model_name='bartheme',
            constraint=models.UniqueConstraint(fields=('bar', 'theme'), name='unique_bar_theme'),
        ),
        migrations.AddConstraint(
            model_name='barparticipant',
            constraint=models.UniqueConstraint(fields=('bar', 'participant'), name='unique_bar_participant'),
        ),
    ]
