# Generated by Django 4.0 on 2023-02-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_photo'),
        ('core', '0003_bar_theme_alter_drink_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdrink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь'),
        ),
    ]
