# Generated by Django 4.0 on 2023-02-24 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userdrink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='degree',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='количество участников за столом'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='degree',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Безалкогольное'), (1, 'Слабоалкогольное'), (2, 'Крепкое')], verbose_name='степень алкогольности'),
        ),
    ]
