# Generated by Django 4.0 on 2023-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bar_degree_alter_bar_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='название'),
        ),
    ]
