# Generated by Django 4.0 on 2023-03-08 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='количество участников за столом'),
        ),
    ]
