# Generated by Django 4.0 on 2023-03-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bar_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('title',), 'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
    ]
